if(WIN32)
  set(NBS_PLATFORM_WIN32 1)
elseif(APPLE)
  set(NBS_PLATFORM_APPLE 1)
elseif(UNIX)
  set(NBS_PLATFORM_LINUX 1)
else()
  message(FATAL_ERROR "Building NBS is only supported on Windows, macOS, and Linux")
endif()
